version: 2
jobs:
  build:
    working_directory: ~/exampleProject
    docker:
      # ちょっとVersion違うけどまーこれで
      - image: hseeberger/scala-sbt:8u222_1.3.7_2.13.1
        auth:
          username: kokodayodevelop
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
            - dependencies
      - run:
          name: compile
          command: sbt compile test:compile
      - save_cache:
          name: "Library cache"
          key: dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}-{{ checksum "project/build.properties" }}-{{ checksum "project/plugins.sbt" }}
          paths:
            # linuxだとここしといた方が良いらしい
            - ~/.cache/coursier/v1
            - ~/.ivy2/cache
            - ~/.sbt
            - ~/.m2
            - modules/domain/target
            - modules/adapters/memory/target
            - modules/adapters/adaptersWeb/target
            - modules/inject/target
            - tests/target
            - apps/web/target
            - apps/cli/target
      - run:
          name: test
          command: sbt test

